//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppleRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppleRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppleRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Загрузка...].
        /// </summary>
        internal static string CddLoadingText {
            get {
                return ResourceManager.GetString("CddLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставьте ваш комментарий или интересующий вопрос.
        /// </summary>
        internal static string Feedback_Comment {
            get {
                return ResourceManager.GetString("Feedback.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания.
        /// </summary>
        internal static string Feedback_Company {
            get {
                return ResourceManager.GetString("Feedback.Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *e-mail.
        /// </summary>
        internal static string Feedback_Email {
            get {
                return ResourceManager.GetString("Feedback.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Имя.
        /// </summary>
        internal static string Feedback_FirstName {
            get {
                return ResourceManager.GetString("Feedback.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Обратная связь&lt;/h1&gt; 
        ///
        ///	&lt;p&gt;Если у вас есть к нам  вопросы или пожелания, используйте форму обратной связи и мы обязательно вам ответим.&lt;/p&gt;.
        /// </summary>
        internal static string Feedback_Header {
            get {
                return ResourceManager.GetString("Feedback.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Фамилия.
        /// </summary>
        internal static string Feedback_LastName {
            get {
                return ResourceManager.GetString("Feedback.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        internal static string Feedback_Position {
            get {
                return ResourceManager.GetString("Feedback.Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string Feedback_Telephone {
            get {
                return ResourceManager.GetString("Feedback.Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за Ваше сообщение. Мы рассмотрим его в ближайшее время..
        /// </summary>
        internal static string Feedback_ThankYou {
            get {
                return ResourceManager.GetString("Feedback.ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка  при отправке.
        /// </summary>
        internal static string MailNotSent {
            get {
                return ResourceManager.GetString("MailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус партнёра*.
        /// </summary>
        internal static string PartnerStatus {
            get {
                return ResourceManager.GetString("PartnerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать полностью статью.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо, Ваша заявка была принята к рассмотрению.&lt;br /&gt;Мы с вами свяжемся в ближайшее время..
        /// </summary>
        internal static string RequestStatusFormThankYou {
            get {
                return ResourceManager.GetString("RequestStatusFormThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все продукты.
        /// </summary>
        internal static string SelectAllSpecialization {
            get {
                return ResourceManager.GetString("SelectAllSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;contentmenu&quot;&gt;
        ///				&lt;table width=&quot;100%&quot;&gt;
        ///					&lt;tbody&gt;&lt;tr&gt;
        ///						&lt;td&gt;
        ///							&lt;img alt=&quot;&quot; src=&quot;../images/contentmenu_separator2.gif&quot;/&gt;&lt;a href=&quot;/ru/support/Warranty.aspx&quot;&gt;Гарантийные&lt;br/&gt; обязательства Apple&lt;/a&gt;						&lt;/td&gt;
        ///						&lt;td&gt;
        ///							&lt;img alt=&quot;&quot; src=&quot;../images/contentmenu_separator2.gif&quot;/&gt;&lt;a href=&quot;/ru/support/AASP.aspx&quot;&gt;Получение статуса авторизованного&lt;br/&gt; сервисного центра по продукции Apple&lt;/a&gt;						&lt;/td&gt;
        ///						&lt;td&gt;
        ///							&lt;img alt=&quot;&quot; src=&quot;../images/contentmenu_separator2.gif&quot;/&gt;&lt;a hre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceCenters_SecondMenu {
            get {
                return ResourceManager.GetString("ServiceCenters.SecondMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table  align=&quot;center&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;span&gt;Линия горячей поддержки: &lt;div class=&apos;phone&apos;&gt;0 800 302 777 0&lt;/div&gt;&lt;br /&gt;
        ///                        c 9:00 до 18:00 поможем вам на русском, украинском и английском языках&lt;br /&gt;
        ///&lt;div id=&quot;langauge_selector&quot;&gt;
        ///						
        ///        &lt;a id=&quot;ctl00_Langs_rLangs_ctl00_hlLang&quot; class=&quot;langru activeru&quot; href=&quot;/ru/default.aspx&quot;&gt;&lt;/a&gt;
        ///    
        ///        &lt;a id=&quot;ctl00_Langs_rLangs_ctl01_hlLang&quot; href=&quot;#&quot; class=&quot;langua&quot;&gt;&lt;/a&gt;
        ///    
        ///
        ///
        ///					&lt;/div&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SiteFooter {
            get {
                return ResourceManager.GetString("SiteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализация.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус*.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;contentmenu&quot;&gt;
        ///	&lt;table class=&quot;foursection&quot;&gt;
        ///		&lt;tbody&gt;&lt;tr&gt;
        ///			&lt;td&gt;
        ///				&lt;img src=&quot;/images/contentmenu_separator2.gif&quot; alt=&quot;&quot;&gt;
        ///				&lt;a href=&quot;Consumers.aspx&quot;&gt;Домашние &lt;br&gt;пользователи&lt;/a&gt;
        ///			&lt;/td&gt;
        ///			&lt;td&gt;
        ///				&lt;img src=&quot;/images/contentmenu_separator2.gif&quot; alt=&quot;&quot;&gt;Профессионалы:&lt;br&gt;
        ///				&lt;a href=&quot;ErcProAudio.aspx&quot;&gt;Аудио&lt;/a&gt; | 
        ///				&lt;a href=&quot;ErcProVideo.aspx&quot;&gt;Видео&lt;/a&gt; | 
        ///				&lt;a href=&quot;ErcProPhoto.aspx&quot;&gt;Фото&lt;/a&gt;
        ///			&lt;/td&gt;
        ///			&lt;td&gt;
        ///				&lt;img src=&quot;/images/contentmenu_separator2.gif&quot; alt=&quot;&quot;&gt;
        ///				&lt;a hre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SuccessStories_SecondMenu {
            get {
                return ResourceManager.GetString("SuccessStories.SecondMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истории успеха.
        /// </summary>
        internal static string SuccessStory {
            get {
                return ResourceManager.GetString("SuccessStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
    }
}
